namespace Adamantium.UI.Core.Automation;

/// <summary>What an element is to automation, whatever class draws it: the control types of UI Automation.</summary>
public enum AutomationControlType
{
    Custom,
    Button,
    Calendar,
    CheckBox,
    ComboBox,
    DataGrid,
    DataItem,
    Document,
    Edit,
    Group,
    Header,
    HeaderItem,
    Hyperlink,
    Image,
    List,
    ListItem,
    Menu,
    MenuBar,
    MenuItem,
    Pane,
    ProgressBar,
    RadioButton,
    ScrollBar,
    Separator,
    Slider,
    Spinner,
    SplitButton,
    StatusBar,
    Tab,
    TabItem,
    Table,
    Text,
    Thumb,
    TitleBar,
    ToolBar,
    ToolTip,
    Tree,
    TreeItem,
    Window
}
