<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <Configurations>Release;Debug</Configurations>
        <Platforms>AnyCPU</Platforms>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseEngineSource)' == 'true'">
      <ProjectReference Include="$(AdamantiumEngineDir)Adamantium.Core\Adamantium.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseEngineSource)' != 'true'">
      <PackageReference Include="Adamantium.Core" Version="$(AdamantiumEngineVersion)" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.3.0" />
    </ItemGroup>

</Project>
